export const ErrorMessageCode = {
    // General Error
    UNKNOWN: 'UNKNOWN',
    SYSTEM_GENERAL_ERROR: 'SYSTEM_GENERAL_ERROR',
    DATABASE_ERROR: 'DATABASE_ERROR',
    INVALID_HEADERS: 'INVALID_HEADERS',
    SYNTAX_ERROR: 'SYNTAX_ERROR',
    NOT_FOUND: 'NOT_FOUND',
    INVALID: 'INVALID',

    // Database
    DATABASE_CONNECTION_ERROR: 'DATABASE_CONNECTION_ERROR',
    INSERT_ERROR: 'INSERT_ERROR',
    UPDATE_ERROR: 'UPDATE_ERROR',
    DELETE_ERROR: 'DELETE_ERROR',
    RECORD_NOT_FOUND: 'RECORD_NOT_FOUND',

    // Permision 10000
    PERMISSION_DENIED: 'PERMISSION_DENIED',
};
